
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOAD";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const PAYLOAD_SELECTED = "PAYLOAD_SELECTED";
export const WEBPAYLOAD_SELECTED = "WEBPAYLOAD_SELECTED";
export const WINDOW_LOG_SELECTED = "WINDOW_LOG_SELECTED";
export const NO_VIEW_SELECTED = "NO_VIEW_SELECTED";
export const WEBPAYLOADS = "WEBPAYLOADS";
export const LOAD_WPAYLOAD_PREDICTION = "LOAD_WPAYLOAD_PREDICTION";
export const FINISHED_LOADING_WPAYLOAD_PREDICTION =
  "FINISHED_LOADING_WPAYLOAD_PREDICTION";
export const LOAD_SCAN_RESULTS = "LOAD_SCAN_RESULTS";
export const LOAD_AGENTS = "LOAD_AGENTS";